### ISSUE TITLE
Readme suggests psycopg2 which does not work

### ISSUE THREAD

**Issue by tonjo** [adamhmetal/redbeanpython#4]
In the README:

For PostgreSQL support RedBeanPython requires:

- psycopg2 2.9.9 or newer.

But installing `psycopg2` won't work. You should install `psycopg` instead, or maybe simply add `psycopg2` in [config file](https://github.com/adamhmetal/redbeanpython/blob/main/redbeanpython/config.py)

ERROR with psycopg2:

```
Traceback (most recent call last):
  File "/MY_HOME/rbtest.py", line 3, in <module>
    r.setup('postgresql+psycopg://rb:rbc@localhost/redbeantest')
  File "/MY_HOME/.virtualenvs/redbean/lib/python3.11/site-packages/redbeanpython/facade.py", line 109, in setup
    self._red_bean = RedBean(dsn=dsn, frozen=frozen, directory=directory, namespace=namespace)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/MY_HOME/.virtualenvs/redbean/lib/python3.11/site-packages/redbeanpython/redbean.py", line 101, in __init__
    self.engine = create_engine(self.config.dsn)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/MY_HOME/.virtualenvs/redbean/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/MY_HOME/.virtualenvs/redbean/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/MY_HOME/.virtualenvs/redbean/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 378, in import_dbapi
    import psycopg
ModuleNotFoundError: No module named 'psycopg'
```

**Comment by adamhmetal** [comment]
Thanks for reporting this issue.
Indeed, there was bug in readme and docs.
It was correctly documented in in Compatibility table https://redbeanpython.org/supported_versions/ but incorrectly in readme and introducion page.

I fixed it already. Thanks again :)
